name: guardian-bedrock-e2e

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  guardianprep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get history file from gh-pages branch
        continue-on-error: true
        run: |
          git pull
          git checkout gh-pages
          git pull

      - uses: actions/upload-artifact@master
        with:
          name: allure-report
          path: allure-report
          retention-days: 20

      - uses: actions/upload-artifact@master
        with:
          name: new-allure-report
          path: allure-report
          retention-days: 20

      - name: Back to main branch
        run: git checkout main

  guardiane2e:
    needs: guardianprep
    name: 'Guardian e2e Tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm' 
          
      - name: Install Node dependencies
        run: |
          npm install
          npm i -D allure-playwright
          npm i -D allure-commandline

      - name: Install Playwright Browsers
        run: |
          npm install -D @playwright/test --with-deps
          npx playwright install

      - name: Run Playwright tests
        continue-on-error: true
        run: npx playwright test --reporter=line,allure-playwright
        env:
          TESTACCOUNT_EMAIL: ${{ secrets.TESTACCOUNT_EMAIL }}
          TESTACCOUNT_PASSWORD: ${{ secrets.TESTACCOUNT_PASSWORD }}
          TEST_BASE_URL: ${{ secrets.TEST_BASE_URL }}
          TEST_EXPECT_URL: ${{ secrets.TEST_EXPECT_URL }}

      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Persist history for allure
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history