on:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14 

      - name: Install dependencies and run tests
        run: |
            npm install
            npm install -D @playwright/test --with-deps
            npx playwright install-deps
            npm run test       