name: CI for run UI tests and save report to gh-pages.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Install and exec tests
        run: npm install && npm run test      