name: guardian-bedrock-e2e

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the e2e against'
        required: true
        default: ':stage'
        type: choice
        options:
          - :stage
          - :prod
          - :dev

jobs:
  guardiane2e:
    name: 'Guardian e2e Tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node dependencies
        run: |
          npm ci
          npm i -D allure-playwright
          npm i -D allure-commandline

      - name: Install Playwright Browsers
        run: |
          npm install -D @playwright/test --with-deps
          npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright --retries=2
        env:
          TESTACCOUNT_EMAIL: ${{ secrets.TESTACCOUNT_EMAIL }}
          TESTACCOUNT_PASSWORD: ${{ secrets.TESTACCOUNT_PASSWORD }}
          TEST_BASE_URL: ${{ secrets.TEST_BASE_URL }}
          TEST_EXPECT_URL: ${{ secrets.TEST_EXPECT_URL }}

      - name: generate allure report
        run: allure generate ./allure-results

      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 20      

      - name: upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: allure-report

      - name: Publish to github pages
        uses: actions/deploy-pages@v1
        with:          
          artifact_name: allure-report