name: trigger guardian e2e suite

on:
  workflow_dispatch:
    description: 'Lets user run the guardian e2e suite with env variables'
    inputs:
      browser:
        description: 'Browser to run e2e suite against'
        required: true
        default: 'firefox'
        type: choice
        options:
          - chromium
          - firefox
      environment:
        description: 'Environment to run tests against'
        default: 'prod'
        type: environment
        required: true

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo  Just checking stuff hereeee --||-> ${{ secrets.TEST_ENV }}
        env:
          CI: true
          TESTACCOUNT_EMAIL: ${{ secrets.TESTACCOUNT_EMAIL }}
          TESTACCOUNT_PASSWORD: ${{ secrets.TESTACCOUNT_PASSWORD }}
          TEST_ENV: ${{ secrets.TEST_ENV }}
