name: trigger guardian e2e suite

on:
  workflow_dispatch:
    description: 'Lets user run the guardian e2e suite with env variables'
    inputs:
      browser:
        description: 'Browser to run e2e suite against'
        required: true
        default: 'firefox'
        type: choice
        options:
          - chromium
          - firefox
      environment:
        description: 'Environment to run tests against'
        default: 'prod'
        type: environment
        required: true

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies and run tests
        run: |
          npm install
          npm install -D @playwright/test --with-deps
          npx playwright install
          npm run test
        env:
          CI: true
          TESTACCOUNT_EMAIL: ${{ secrets.TESTACCOUNT_EMAIL }}
          TESTACCOUNT_PASSWORD: ${{ secrets.TESTACCOUNT_PASSWORD }}
          TEST_ENV: ${{ secrets.TEST_ENV }}
